language: php
php:
- '7.0'
- '7.1'

env: NODE_ENV="test"
sudo: false

notifications:
  email: false

before_script:
- nvm install 7
- node --version
- npm install

script: npm test
after_script: npm run coverage
