language: php
sudo: false

env: NODE_BIN="./node-v6.4.0-linux-x64/bin/node" NODE_ENV="test" NPM_CLI="./node-v6.4.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js"
php: '7.0'

install:
- wget https://nodejs.org/dist/v6.4.0/node-v6.4.0-linux-x64.tar.xz
- tar xf node-v6.4.0-linux-x64.tar.xz
- $NODE_BIN $NPM_CLI install

script: $NODE_BIN $NPM_CLI test
after_script: $NODE_BIN $NPM_CLI run coverage
